/* ============================================================
   THE PHOTOGRAPHS ARE REALLY HERE, AND THEY ARE REALLY THEIRS.

   `src/demos/northsideImages.ts` is generated by
   `tools/seed/emit_images.py` out of `tools/seed/extracts/images.json`,
   which `tools/seed/fetch_images.py` wrote from the wire. Four things
   can go wrong between those steps and none of them announces itself:

     1 · a copy named in the map is not in `public/seed-images`, so the
         tile 404s on our OWN origin — the one failure worse than the
         hotlink it replaced, because there is nobody to blame for it;
     2 · a copy sits in `public/seed-images` that nothing names, which
         is dead weight in the repository and, worse, evidence that
         some address quietly changed;
     3 · an address is BOTH held and recorded absent, so what the plate
         says and what the tile draws disagree;
     4 · an address in the map is not an address in the seed — the way
         a substituted photograph would have to enter.

   And the reasons are prose that lands inside a sentence somebody
   reads, so they are held to the same shape `imageSources.test.ts`
   holds `MEASURED_CLOSED` to.

   Read through Vite's own resolver rather than `node:fs`, for the
   reason `entryChunk.test.ts` gives: `@types/node` is not a dependency
   of this project.
   ============================================================ */
import { describe, expect, it } from 'vitest'

/* the module registers on import; it reads no DOM */
const { NORTHSIDE_PICTURES, HELD, ABSENT_HOSTS, ABSENT } = await import(
  './northsideImages'
)

/** every file actually sitting in `public/seed-images`, by name */
const ON_DISK = new Set(
  Object.keys(
    import.meta.glob('/public/seed-images/*.webp', { query: '?url', import: 'default' }),
  ).map((k) => k.replace(/^.*\//, '')),
)

/** THE MEASUREMENT THE MAP WAS GENERATED FROM, read as TEXT rather
 *  than imported as JSON: `resolveJsonModule` is off in
 *  tsconfig.app.json, and turning it on for one test file is a
 *  compiler setting bought with a test. */
interface ImageManifest {
  _meta: { totalBytes: number; obtained: number; unavailable: number; measured: string }
  images: Array<{ url: string; host: string; file?: string; why?: string; bytes?: number }>
}
const RAW = import.meta.glob('/tools/seed/extracts/images.json', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>
const manifest = JSON.parse(Object.values(RAW)[0] ?? '{}') as ImageManifest

describe('the copies the repository holds', () => {
  it('found something to check at all', () => {
    expect(HELD.length).toBeGreaterThan(100)
    expect(ON_DISK.size).toBeGreaterThan(100)
  })

  it('names a file that exists for every address it claims to hold', () => {
    const missing = HELD.filter(([, file]) => !ON_DISK.has(file)).map(([url]) => url)
    expect(missing).toEqual([])
  })

  it('leaves no picture in the repository that nothing points at', () => {
    const named = new Set(HELD.map(([, file]) => file))
    expect([...ON_DISK].filter((f) => !named.has(f))).toEqual([])
  })

  it('gives each address one file and each file one address', () => {
    expect(new Set(HELD.map(([url]) => url)).size).toBe(HELD.length)
    expect(new Set(HELD.map(([, file]) => file)).size).toBe(HELD.length)
  })

  it('records the ORIGINAL size, which is the only size worth printing', () => {
    for (const [url, , w, h] of HELD) {
      expect(w, url).toBeGreaterThan(0)
      expect(h, url).toBeGreaterThan(0)
    }
  })

  it('never says a picture is both held and unavailable', () => {
    const held = new Set(HELD.map(([url]) => url))
    const deadHosts = new Set(ABSENT_HOSTS.map(([host]) => host))
    expect(ABSENT.filter(([url]) => held.has(url))).toEqual([])
    /* and no address on a host declared wholly dead may have a copy */
    expect(
      [...held].filter((url) => deadHosts.has(new URL(url).host)),
      'an address on a host recorded as serving nothing',
    ).toEqual([])
  })
})

describe('what the map says against what was measured', () => {
  it('holds exactly the addresses the fetch obtained', () => {
    const obtained = manifest.images.filter((r) => r.file).map((r) => r.url)
    expect([...HELD.map(([u]) => u)].sort()).toEqual([...obtained].sort())
  })

  it('accounts for every address the fetch could not obtain', () => {
    const deadHosts = new Set(ABSENT_HOSTS.map(([host]) => host))
    const byAddress = new Set(ABSENT.map(([url]) => url))
    const unexplained = manifest.images
      .filter((r) => !r.file)
      .filter((r) => !deadHosts.has(r.host) && !byAddress.has(r.url))
    expect(unexplained).toEqual([])
  })

  it('counts and weighs what is really there', () => {
    expect(NORTHSIDE_PICTURES.held).toBe(manifest._meta.obtained)
    expect(NORTHSIDE_PICTURES.absent).toBe(manifest._meta.unavailable)
    expect(NORTHSIDE_PICTURES.bytes).toBe(manifest._meta.totalBytes)
    expect(NORTHSIDE_PICTURES.measured).toBe(manifest._meta.measured)
    /* the ceiling is a decision, not an accident: a few hundred
       photographs may not become a repository nobody wants to clone.
       If a re-fetch crosses it, downscale further or drop something —
       do not raise it without saying what was measured. */
    expect(NORTHSIDE_PICTURES.bytes).toBeLessThan(6_000_000)
  })
})

describe('the reasons, as words somebody reads', () => {
  const reasons = [
    ...ABSENT_HOSTS.map(([, why]) => why),
    ...ABSENT.map(([, why]) => why),
  ]

  it('reads as a clause as well as a sentence', () => {
    expect(reasons.length).toBeGreaterThan(0)
    for (const why of reasons) {
      /* the module index joins these with commas and "and" */
      expect(why).not.toMatch(/^(this|it|the picture)\b/i)
      expect(why).not.toMatch(/[.!?]$/)
      /* and it names the host, or the list it lands in says nothing
         about which site is being talked about */
      expect(why, why).toMatch(/[a-z0-9-]+\.[a-z.]{2,}/)
    }
  })

  it('never invents a stand-in, a caption or an apology', () => {
    for (const why of reasons) {
      expect(why).not.toMatch(/similar|instead|stand-in|placeholder|sorry/i)
    }
  })
})

/* ============================================================
   AND EVERY ADDRESS IS ONE THE WORKBOOK REALLY TYPED.

   This is the assertion that makes the rest of the file safe. A map
   from address to photograph is exactly the shape a SUBSTITUTION
   would take — one row quietly given another boat's picture, which is
   the failure IMAGE_SPEC.md §6.6 records the root app committing
   ("same hull family", nothing in the schema saying so, shown to a
   customer on a quote). It cannot happen here while every key is an
   address the seed itself carries and every seeded address is
   accounted for exactly once.

   The seed is behind `seedChunk`; tests are exempt from that boundary
   (entryChunk.test.ts says why) and this one has to build the set to
   check it.
   ============================================================ */
const { buildNorthsideProject } = await import('./northside')

/** every distinct address in a picture cell of the seed */
function seededAddresses(): Set<string> {
  const p = buildNorthsideProject()
  const picture = new Set<string>()
  for (const e of p.entities) {
    for (const f of e.fields) if (f.type === 'image') picture.add(f.id)
  }
  const out = new Set<string>()
  for (const rows of Object.values(p.rowsByEntity)) {
    for (const row of rows) {
      for (const [fieldId, value] of Object.entries(row.values)) {
        if (!picture.has(fieldId) || !Array.isArray(value)) continue
        for (const img of value) out.add(img.src)
      }
    }
  }
  return out
}

describe('the map against the seed', () => {
  const addresses = seededAddresses()

  it('reads the seed at all', () => {
    expect(addresses.size).toBeGreaterThan(150)
  })

  it('holds no address the catalogue does not carry', () => {
    expect(HELD.map(([url]) => url).filter((url) => !addresses.has(url))).toEqual([])
    expect(ABSENT.map(([url]) => url).filter((url) => !addresses.has(url))).toEqual([])
  })

  it('accounts for every address the catalogue carries, exactly once', () => {
    /* THREE STATES, NOT TWO, AND THE THIRD IS COUNTED RATHER THAN
       ASSUMED EMPTY. An address is HELD (there is a copy under
       public/seed-images), or EXPLAINED (the fetch was made and
       refused, and the reason is recorded), or UNMEASURED — nobody
       has asked yet. The third became non-empty when the catalogue
       went to full scale: Highfield alone went from 40 hulls to 588
       and brought 183 more addresses with it, and taking those
       pictures means a few hundred requests to nine third-party
       servers, which is a decision rather than a side effect of a
       regeneration (SEED_AT_FULL_SCALE.md §2.2).

       An unmeasured address behaves exactly like a refused one: the
       row keeps its address and the app draws "Held as a link".
       Nothing is invented for it. What this asserts is that the
       COUNT is right — `NORTHSIDE_PICTURES.unmeasured` is what the
       seed really carries and nothing else — so the gap cannot grow
       or vanish without turning this red. Clear it by running
       `python tools/seed/fetch_images.py`. */
    const held = new Set(HELD.map(([url]) => url))
    const deadHosts = new Set(ABSENT_HOSTS.map(([host]) => host))
    const byAddress = new Set(ABSENT.map(([url]) => url))
    const measured = new Set(manifest.images.map((r) => r.url))
    const unmeasured: string[] = []
    const unaccounted: string[] = []
    const twice: string[] = []
    for (const url of addresses) {
      const dead = deadHosts.has(new URL(url).host) || byAddress.has(url)
      if (held.has(url) && dead) twice.push(url)
      if (held.has(url) || dead) continue
      if (measured.has(url)) unaccounted.push(url)
      else unmeasured.push(url)
    }
    /* a MEASURED address that is neither held nor explained is a
       generator bug, and stays a hard zero */
    expect(unaccounted).toEqual([])
    expect(twice).toEqual([])
    expect(unmeasured.length).toBe(NORTHSIDE_PICTURES.unmeasured)
  })

  it('says how many pictures have not been asked for, out loud', () => {
    /* The figure is allowed to be non-zero. It is not allowed to be
       a surprise: it is exported, it is in the generated file's own
       header, and `python tools/seed/emit.py` prints it with the
       command that clears it. */
    expect(NORTHSIDE_PICTURES.unmeasured).toBe(234)
    expect(NORTHSIDE_PICTURES.held + NORTHSIDE_PICTURES.absent).toBe(manifest.images.length)
  })
})
